Task02 [Рябинин]
csu-mk-2020/4-java-oop-basic pull request #17
Opened 2020-10-01 08:36 UTC by PavelRyabinin

2020-10-09 06:19 UTC, batarelkin requested changes

2020-10-09 06:19 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +    private int _seconds;
зачем "_" в названии полей?

2020-10-09 06:19 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +        normalize();
исключение выбросится уже после того, как объект изменит своё состояние на некорректное

2020-10-09 06:19 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +        setSeconds(seconds);
```
TimeSpan ts = new TimeSpan(0,60,0)
ts.getHours(); // -> 0
ts.getMinutes(); // -> 60
ts.add(new TimeSpan(0, 0, 0));
ts.getHours(); // -> 1
ts.getMinutes(); // -> 0
```
Состояние объекта изменяется, не смотря на то, что по факту значение не изменилось.

2020-10-10 03:50 UTC, BatanGaming commented on task02/src/com/example/task02/TimeSpan.java
> +    private int _seconds;
Привычка именования приватных полей

2020-10-10 03:54 UTC, BatanGaming commented on task02/src/com/example/task02/TimeSpan.java
> +        normalize();
Исключения не будет, т.к в normalize исключение выбрасывается только при 
`if (_hours < 0) {
    throw new IllegalStateException();
}`
Невозможно создать объект с отрицательными полями, поэтому при сложении hours никак не станет отрицательным

2020-10-10 04:07 UTC, BatanGaming commented on task02/src/com/example/task02/TimeSpan.java
> +        setSeconds(seconds);
Исправил

2020-10-16 06:47 UTC, batarelkin requested changes

2020-10-16 06:47 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +    private int _seconds;
Надо исправить, это не java style

2020-10-16 06:47 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +            throw new IllegalStateException();
надо какое-то объяснение (message) добавить, а то не понятна причина ошибки

2020-10-16 10:25 UTC, BatanGaming commented on task02/src/com/example/task02/TimeSpan.java
> +            throw new IllegalStateException();
Исправил

2020-10-23 06:10 UTC, closed without merging