Task04 [Рябинин]
csu-mk-2020/4-java-oop-basic pull request #19
Opened 2020-10-01 08:37 UTC by PavelRyabinin

2020-10-09 06:21 UTC, batarelkin requested changes

2020-10-09 06:21 UTC, batarelkin commented on task04/src/com/example/task04/Line.java
> +    private final Point _p1;
зачем "_" в названии полей?

2020-10-10 03:56 UTC, BatanGaming commented on task04/src/com/example/task04/Line.java
> +    private final Point _p1;
Привычка именования приватных полей

2020-10-16 06:47 UTC, batarelkin commented on task04/src/com/example/task04/Line.java
> +    private final Point _p1;
переименуйте.

2020-10-16 07:10 UTC, closed without merging