Task02 [Саитгалин]
csu-mk-2020/4-java-oop-basic pull request #2
Opened 2020-09-20 08:21 UTC by Vinges541

2020-09-25 04:48 UTC, batarelkin requested changes

2020-09-25 04:48 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +            this.minutes = minutes;
В таких случаях ни чего не делать не самый хороший вариант. Лучше выбрасывать исключение, например:
```
if (minutes >= 60 || minutes < 0) {
  throw new IllegalArgumentException("Минуты должны быть в диапазоне 0-59")
}
```

2020-09-25 04:48 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +    TimeSpan(int hours, int minutes, int seconds){
Надо добавить проверку на неотрицательность чисел.

2020-09-25 04:48 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +            this.seconds = seconds;
аналогично

2020-09-25 04:48 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +        normalize(this.denormalize()+time.denormalize());
Нужно учесть, что кто-то может передать в качестве аргумента null, тогда произойдёт исключение NullPointerException. Лучше проверять
```
if (time == null) {
  throw new IllegalArgumentException("аргумент не может быть null")
}
```
Либо
```
Objects.requireNonNull(time, "аргумент не может быть null")
```

2020-09-25 04:48 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +    TimeSpan(int hours, int minutes, int seconds){
Во всех set методах аналогично

2020-10-09 04:55 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +        if (seconds >= 60 || seconds < 0) {
Если по вашему коду сделать следующее:
```
TimeSpan ts = new TimeSpan(0, 60, 60)
ts.getHours(); // -> 0
ts.add(new TimeSpan(0, 0, 0));
ts.getHours(); // -> 1
```
То получится, что добавление (или вычитание) пустого временного интервала меняет внутреннее состояние, что не очень хорошо.

2020-10-09 05:13 UTC, Vinges541 commented on task02/src/com/example/task02/TimeSpan.java
> +        if (seconds >= 60 || seconds < 0) {
ещё в первой строчке вылетит с IllegalArgumentException

2020-10-16 06:06 UTC, closed without merging