Task05 [Рябинин]
csu-mk-2020/4-java-oop-basic pull request #20
Opened 2020-10-01 08:38 UTC by PavelRyabinin

2020-10-09 06:22 UTC, batarelkin requested changes

2020-10-09 06:22 UTC, batarelkin commented on task05/src/com/example/task05/Point.java
> +    private double _x;
"_" в названии

2020-10-09 06:22 UTC, batarelkin commented on task05/src/com/example/task05/PolygonalLine.java
> +            addPoint(points[i]);
В описании "Устанавливает", а вы добавляете

2020-10-10 04:11 UTC, BatanGaming commented on task05/src/com/example/task05/Point.java
> +    private double _x;
Привычка именования приватных полей

2020-10-10 04:11 UTC, BatanGaming commented on task05/src/com/example/task05/PolygonalLine.java
> +            addPoint(points[i]);
Исправил

2020-10-16 06:48 UTC, batarelkin commented on task05/src/com/example/task05/Point.java
> +    private double _x;
переименуйте, пожалуйста

2020-10-16 10:25 UTC, BatanGaming commented on task05/src/com/example/task05/Point.java
> +    private double _x;
Исправил

2020-10-23 06:10 UTC, closed without merging