[Khazov] task05
csu-mk-2020/4-java-oop-basic pull request #26
Opened 2020-10-05 15:12 UTC by redrockstyle

2020-10-09 05:57 UTC, batarelkin requested changes

2020-10-09 05:57 UTC, batarelkin commented on task05/src/com/example/task05/PolygonalLine.java
> +                this.points.add(new Point(p.getX(), p.getY()));
В описании метода "Устанавливает точки", а вы добавляете точки

2020-10-16 07:19 UTC, batarelkin requested changes

2020-10-16 07:19 UTC, batarelkin commented on task05/src/com/example/task05/PolygonalLine.java
> +        } else throw new IllegalArgumentException("аргумент пуст");
если null, то возникнет исключительная ситуация, но список точек уже будет очищен...

2020-10-18 07:19 UTC, redrockstyle commented on task05/src/com/example/task05/PolygonalLine.java
> +        } else throw new IllegalArgumentException("аргумент пуст");
исправил

2020-11-20 04:46 UTC, closed without merging