Task 02 [Теплинский]
csu-mk-2020/4-java-oop-basic pull request #28
Opened 2020-10-07 15:26 UTC by ThatSeemsLegit

2020-10-09 05:16 UTC, batarelkin requested changes

2020-10-09 05:16 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +    void setHrs(int hrs) {
1. Почему конструктор public, а методы package private?

2020-10-09 05:16 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +    void setSecs(int secs) {
не экономьте на буквах, getSeconds сразу понятно что делает, а getSecs нет

2020-10-09 05:16 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +        this.hrs = hrs;
А timestamp забыли поменять...

2020-10-13 17:49 UTC, ThatSeemsLegit commented on task02/src/com/example/task02/TimeSpan.java
> +    void setSecs(int secs) {
Поправил

2020-10-16 07:24 UTC, batarelkin requested changes

2020-10-16 07:24 UTC, batarelkin commented on task02/src/com/example/task02/TimeSpan.java
> +        this.timestamp = this.timestamp + timeSpan.timestamp;
Учитывая проверки в конструкторе и set методах у вас TimeSpan не может быть меньше 0 и больше суток (на самом деле 24 часов, 59 минут, 59 секунд), но если сложить (или вычесть) два TimeSpan, то результат может выйти за границы.

2020-10-20 19:06 UTC, ThatSeemsLegit commented on task02/src/com/example/task02/TimeSpan.java
> +    void setHrs(int hrs) {
Поправил

2020-10-20 19:06 UTC, ThatSeemsLegit commented on task02/src/com/example/task02/TimeSpan.java
> +        this.hrs = hrs;
Поправил еще в прошлом коммите

2020-10-20 19:09 UTC, ThatSeemsLegit commented on task02/src/com/example/task02/TimeSpan.java
> +        this.timestamp = this.timestamp + timeSpan.timestamp;
По поводу сложения согласен, по поводу вычитания не совсем понял, можно получить отрицательный timestamp, но это уже будут дела пользователя. Могу сделать, что на отрицательном мы кидаем исключение, если надо

2020-10-23 06:44 UTC, closed without merging