Task 03 [Теплинский]
csu-mk-2020/4-java-oop-basic pull request #29
Opened 2020-10-07 15:27 UTC by ThatSeemsLegit

2020-10-09 05:17 UTC, batarelkin requested changes

2020-10-09 05:17 UTC, batarelkin commented on task03/src/com/example/task03/ComplexNumber.java
> +    ComplexNumber(double re, double im) {
Почему package private?

2020-10-09 05:17 UTC, batarelkin commented on task03/src/com/example/task03/ComplexNumber.java
> +        if (rhs == null) {
Используйте лучше Objects.requireNotNull(rhs, "message")

2020-10-13 17:49 UTC, ThatSeemsLegit commented on task03/src/com/example/task03/ComplexNumber.java
> +        if (rhs == null) {
Поправил

2020-10-16 07:25 UTC, batarelkin requested changes

2020-10-16 07:25 UTC, batarelkin commented on task03/src/com/example/task03/ComplexNumber.java
> +    double re;
внизу поправили модификаторы, а тут нет. Ещё и get методов нет. Как снаружи получить значение комплексного числа?

2020-10-20 19:12 UTC, ThatSeemsLegit commented on task03/src/com/example/task03/ComplexNumber.java
> +    double re;
Добавил модификаторы и добавил get-методы для полей

2020-10-23 06:44 UTC, closed without merging