Task 04 [Теплинский]
csu-mk-2020/4-java-oop-basic pull request #30
Opened 2020-10-07 15:27 UTC by ThatSeemsLegit

2020-10-09 05:20 UTC, batarelkin requested changes

2020-10-09 05:20 UTC, batarelkin commented on task04/src/com/example/task04/Line.java
> +            throw new NullPointerException("");
Лучше по отдельности, используя Objects.requireNotNull(obj, message), т.к. можно сразу объястить что не должно быть null.
Из данного кода не понятно какой параметр оказался null и придётся отлаживать...

2020-10-09 05:20 UTC, batarelkin commented on task04/src/com/example/task04/Line.java
> +        if (p == null) {
Либо Objects.requireNotNull(obj, message) либо тогда выбрасывайте IllegalArgumentException

2020-10-13 17:49 UTC, ThatSeemsLegit commented on task04/src/com/example/task04/Line.java
> +            throw new NullPointerException("");
Поправил

2020-10-16 07:29 UTC, batarelkin commented on task04/src/com/example/task04/Line.java
> +        this.p2 = p2;
Эту запись можно сократить то:
```java
this.p1 = Objects.requireNonNull(p1);
this.p2 = Objects.requireNonNull(p2);
```

2020-10-16 07:29 UTC, closed without merging