Task 05 [Теплинский]
csu-mk-2020/4-java-oop-basic pull request #31
Opened 2020-10-07 15:28 UTC by ThatSeemsLegit

2020-10-09 05:22 UTC, batarelkin requested changes

2020-10-09 05:22 UTC, batarelkin commented on task05/src/com/example/task05/Point.java
> +            throw new IllegalArgumentException();
а где сообщение?

2020-10-09 05:22 UTC, batarelkin commented on task05/src/com/example/task05/Point.java
> +            throw new IllegalArgumentException();
аналогично...

2020-10-09 05:22 UTC, batarelkin commented on task05/src/com/example/task05/PolygonalLine.java
> +            throw new IllegalArgumentException();
аналогично

2020-10-09 05:22 UTC, batarelkin commented on task05/src/com/example/task05/PolygonalLine.java
> +            this.points.add(new Point(point));
В описании метода "Устанавливает точки", а по коду вы их добавляете

2020-10-13 17:49 UTC, ThatSeemsLegit commented on task05/src/com/example/task05/Point.java
> +            throw new IllegalArgumentException();
Поправил

2020-10-16 07:29 UTC, batarelkin commented on task05/src/com/example/task05/Point.java
> +            throw new IllegalArgumentException();
не вижу...

2020-10-20 19:39 UTC, ThatSeemsLegit commented on task05/src/com/example/task05/Point.java
> +            throw new IllegalArgumentException();
Странно, и правда. Теперь вроде бы точно поправил

2020-10-20 19:39 UTC, ThatSeemsLegit commented on task05/src/com/example/task05/PolygonalLine.java
> +            this.points.add(new Point(point));
Не совсем понял суть замечания

2020-10-23 06:33 UTC, batarelkin requested changes

2020-10-23 06:33 UTC, batarelkin commented on task05/src/com/example/task05/PolygonalLine.java
> +            this.points.add(new Point(point));
Упрощённый пример того, что у вас:
```
int x;

public void setX(int x) {
  this.x += x
}
```
Требуется не добавить точки, а установить ровно те, что передались

2020-10-23 10:00 UTC, ThatSeemsLegit commented on task05/src/com/example/task05/PolygonalLine.java
> +            this.points.add(new Point(point));
Вроде бы пофиксил

2020-11-20 04:43 UTC, closed without merging